# Линейная алгебра

### Импорт библиотек

In [92]:
import numpy as np
from scipy import linalg

## 1. Матрицы

In [5]:
v_hor_np = np.array([1, 2])
v_hor_np

array([1, 2])

In [4]:
v_hor_zero = np.zeros([1, 5])
v_hor_zero

array([[0., 0., 0., 0., 0.]])

In [6]:
v_hor_one = np.ones([1, 5])
v_hor_one

array([[1., 1., 1., 1., 1.]])

In [7]:
v_vert_zero = np.zeros([5, 1])
v_vert_zero

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [10]:
m_sqr_arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
m_sqr_arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
m_sqr_mx = np.matrix([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
m_sqr_mx

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [11]:
m_diag = [[1, 0, 0], [0, 5, 0], [0, 0, 9]]
m_diag_np = np.matrix(m_diag)
m_diag_np

matrix([[1, 0, 0],
        [0, 5, 0],
        [0, 0, 9]])

In [12]:
diag = np.diag(m_sqr_mx)
diag

array([1, 5, 9])

In [13]:
m_diag_np = np.diag(np.diag(m_sqr_mx))
m_diag_np

array([[1, 0, 0],
       [0, 5, 0],
       [0, 0, 9]])

In [14]:
m_eye = np.eye(3)
m_eye

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [18]:
a = np.matrix([[1, 2, 3],[4, 5, 6], [7, 8, 9]])
a

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [19]:
a.transpose()

matrix([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]])

In [21]:
(a.T).T

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [22]:
a

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [23]:
b = a.T

In [24]:
np.linalg.det(a)

0.0

In [25]:
np.linalg.det(b)

0.0

In [26]:
3 * a

matrix([[ 3,  6,  9],
        [12, 15, 18],
        [21, 24, 27]])

In [27]:
0 * a

matrix([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [28]:
a + b

matrix([[ 2,  6, 10],
        [ 6, 10, 14],
        [10, 14, 18]])

Умножение матриц это уже более сложная операция, по сравнению с рассмотренными выше. Умножать можно только матрицы, отвечающие следующему требованию: количество столбцов первой матрицы должно быть равно числу строк второй матрицы.

In [29]:
a = np.matrix([[1, 2, 3], [4, 5, 6]])
a

matrix([[1, 2, 3],
        [4, 5, 6]])

In [31]:
b = np.matrix([[7, 8], [9, 1], [2, 3]])
b

matrix([[7, 8],
        [9, 1],
        [2, 3]])

In [32]:
a * b

matrix([[31, 19],
        [85, 55]])

In [33]:
np.dot(a, b)

matrix([[31, 19],
        [85, 55]])

In [37]:
v = np.dot(b, a)
v

matrix([[39, 54, 69],
        [13, 23, 33],
        [14, 19, 24]])

Определитель матрицы размера   ( -го порядка) является одной из ее численных характеристик. Определитель матрицы   обозначается как   или   , его также называют детерминантом.

In [41]:
v

matrix([[39, 54, 69],
        [13, 23, 33],
        [14, 19, 24]])

In [42]:
c = np.linalg.inv(v)
c

matrix([[ 1.08259606e+14, -2.16519213e+13, -2.81474977e+14],
        [-2.16519213e+14,  4.33038426e+13,  5.62949953e+14],
        [ 1.08259606e+14, -2.16519213e+13, -2.81474977e+14]])

In [43]:
np.linalg.inv(c)

matrix([[13.12, 18.56, 24.  ],
        [ 3.2 ,  9.6 , 16.  ],
        [ 4.8 ,  6.4 ,  8.  ]])

Ранг матрицы является еще одной важной численной характеристикой. Рангом называют максимальное число линейно независимых строк (столбцов) матрицы. Линейная независимость означает, что строки (столбцы) не могут быть линейно выражены через другие строки (столбцы).

In [45]:
m = np.eye(4)
m

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [46]:
np.linalg.matrix_rank(m)

4

## 2. Решение систем линейных уравнений

In [49]:
A = np.matrix('3 -1 2; 1 4 -1; 2 3 1')
A

matrix([[ 3, -1,  2],
        [ 1,  4, -1],
        [ 2,  3,  1]])

In [51]:
B = np.matrix('-4; 10; 8')
B

matrix([[-4],
        [10],
        [ 8]])

In [53]:
A_inv = np.linalg.inv(A)
A_inv

matrix([[ 0.5       ,  0.5       , -0.5       ],
        [-0.21428571, -0.07142857,  0.35714286],
        [-0.35714286, -0.78571429,  0.92857143]])

In [55]:
X = A_inv.dot(B)
X

matrix([[-1.],
        [ 3.],
        [ 1.]])

Если ранг расширенной матрицы равен рангу главной матрицы системы, то такая система уравнений будет совместной, в противном случае - несовместной. Совместная система имеет одно решение, если ее ранг равен числу неизвестных, если ранг меньше числа неизвестных, то число решений бесконечное множество.

In [56]:
X = np.linalg.solve(A, B)
X

matrix([[-1.],
        [ 3.],
        [ 1.]])

## 3. Основы векторной алгебры

In [57]:
A = np.array([1, 2, 3])
A

array([1, 2, 3])

In [59]:
B = np.array([3, 5, 2])
B

array([3, 5, 2])

In [61]:
AB = B - A
AB

array([ 2,  3, -1])

In [63]:
AB = np.array([6, 7, 2])
AB

array([6, 7, 2])

In [64]:
AB_norm = np.linalg.norm(AB)
AB_norm

9.433981132056603

In [65]:
A

array([1, 2, 3])

In [66]:
B

array([3, 5, 2])

In [67]:
A + B

array([4, 7, 5])

In [68]:
A - B

array([-2, -3,  1])

In [69]:
2 * A

array([2, 4, 6])

Скалярное произведение двух векторов

In [72]:
a = np.array([2, 7, 3])
a

array([2, 7, 3])

In [73]:
b = np.array([5, 9, 3])
b

array([5, 9, 3])

In [74]:
a @ b

82

Векторное произведение двух векторов

In [75]:
a

array([2, 7, 3])

In [76]:
b

array([5, 9, 3])

In [77]:
a_norm = np.linalg.norm(a)
a_norm

7.874007874011811

In [78]:
b_norm = np.linalg.norm(b)
b_norm

10.723805294763608

In [79]:
cos_f = (a @ b) / (a_norm * b_norm)
cos_f

0.9711114784134267

In [80]:
sin_f = np.sqrt(1 - cos_f ** 2)
sin_f

0.23862626949623264

In [81]:
c = a_norm * b_norm * sin_f
c

20.149441679609886

In [84]:
np.cross(a, b)

array([ -6,   9, -17])

Смешанное произведение трех векторов

In [85]:
a = [2, 7, 3]
b = [5, 9, 3]
c = [7, 4, 5]
vmp = np.matrix([a, b, c])
vmp

matrix([[2, 7, 3],
        [5, 9, 3],
        [7, 4, 5]])

In [86]:
np.linalg.det(vmp)

-90.99999999999997

## 4. Разложения матриц

LU-разложение матрицы

In [88]:
A = np.array([[4, 1, 3], [8, 1, 8], [-12, -4, -6]])
A

array([[  4,   1,   3],
       [  8,   1,   8],
       [-12,  -4,  -6]])

In [93]:
linalg.lu(A)

(array([[0., 0., 1.],
        [0., 1., 0.],
        [1., 0., 0.]]), array([[ 1.        ,  0.        ,  0.        ],
        [-0.66666667,  1.        ,  0.        ],
        [-0.33333333,  0.2       ,  1.        ]]), array([[-12.        ,  -4.        ,  -6.        ],
        [  0.        ,  -1.66666667,   4.        ],
        [  0.        ,   0.        ,   0.2       ]]))